import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";
import { UserProvider } from "@/components/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-white`}>
        <UserProvider>
          <div className="bg-white text-neutral-800 p-3 md:p-8 max-h-screen overflow-scroll md:overflow-hidden">
            <Link
              href="/"
              className="w-fit px-3 py-1.5 rounded-lg flex gap-1 items-center border-[0.5px] border-neutral-400 md:absolute md:z-20"
            >
              <ChevronLeft className="h-5 w-5" />
              <h2 className="text-sm">Back</h2>
            </Link>
            {children}
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
