export const scanResult = {
  scan_id: 27,
  scan_type: "username",
  scan_value: "toye_oy",
  risk_score: 60,
  created_at: "2025-04-20T21:05:22.000Z",
  findings: {
    breaches: [],
    profiles: [
      {
        id: 8,
        scan_id: 27,
        source: "twitter.com",
        data_type: "profile",
        data_value: "Twitter profile: twitter.com/toye_oy",
        sensitivity_level: "medium",
        breach_date: null,
        context: null,
        created_at: "2025-04-20T21:05:24.000Z",
        updated_at: "2025-04-20T21:05:24.000Z",
        recommendations: [
          {
            id: 22,
            finding_id: 8,
            recommendation:
              "Review and update privacy settings on all your social media accounts",
            action_url: "https://example.com/social-media-privacy",
            priority: "medium",
            created_at: "2025-04-20T21:05:24.000Z",
            updated_at: "2025-04-20T21:05:24.000Z",
          },
          {
            id: 23,
            finding_id: 8,
            recommendation:
              "Check and limit public information on your profiles (twitter.com)",
            action_url: "https://example.com/limit-profile-info",
            priority: "medium",
            created_at: "2025-04-20T21:05:24.000Z",
            updated_at: "2025-04-20T21:05:24.000Z",
          },
          {
            id: 24,
            finding_id: 8,
            recommendation:
              "Regularly monitor your digital footprint by performing periodic scans",
            action_url: "https://example.com/regular-monitoring",
            priority: "medium",
            created_at: "2025-04-20T21:05:24.000Z",
            updated_at: "2025-04-20T21:05:24.000Z",
          },
        ],
      },
      {
        id: 10,
        scan_id: 27,
        source: "instagram.com",
        data_type: "profile",
        data_value: "Instagram profile: instagram.com/toye_oy",
        sensitivity_level: "medium",
        breach_date: null,
        context: null,
        created_at: "2025-04-20T21:05:24.000Z",
        updated_at: "2025-04-20T21:05:24.000Z",
        recommendations: [
          {
            id: 26,
            finding_id: 10,
            recommendation:
              "Review and update privacy settings on all your social media accounts",
            action_url: "https://example.com/social-media-privacy",
            priority: "medium",
            created_at: "2025-04-20T21:05:24.000Z",
            updated_at: "2025-04-20T21:05:24.000Z",
          },
          {
            id: 27,
            finding_id: 10,
            recommendation:
              "Check and limit public information on your profiles (instagram.com)",
            action_url: "https://example.com/limit-profile-info",
            priority: "medium",
            created_at: "2025-04-20T21:05:24.000Z",
            updated_at: "2025-04-20T21:05:24.000Z",
          },
          {
            id: 28,
            finding_id: 10,
            recommendation:
              "Regularly monitor your digital footprint by performing periodic scans",
            action_url: "https://example.com/regular-monitoring",
            priority: "medium",
            created_at: "2025-04-20T21:05:24.000Z",
            updated_at: "2025-04-20T21:05:24.000Z",
          },
        ],
      },
    ],
    exposed_data: [],
    insights: [],
    other: [
      {
        id: 9,
        scan_id: 27,
        source: "reddit.com",
        data_type: "posts",
        data_value: "Reddit posts by u/toye_oy",
        sensitivity_level: "medium",
        breach_date: null,
        context: null,
        created_at: "2025-04-20T21:05:24.000Z",
        updated_at: "2025-04-20T21:05:24.000Z",
        recommendations: [
          {
            id: 25,
            finding_id: 9,
            recommendation:
              "Regularly monitor your digital footprint by performing periodic scans",
            action_url: "https://example.com/regular-monitoring",
            priority: "medium",
            created_at: "2025-04-20T21:05:24.000Z",
            updated_at: "2025-04-20T21:05:24.000Z",
          },
        ],
      },
    ],
  },
  all_findings: [
    {
      id: 8,
      scan_id: 27,
      source: "twitter.com",
      data_type: "profile",
      data_value: "Twitter profile: twitter.com/toye_oy",
      sensitivity_level: "high",
      breach_date: null,
      context: null,
      created_at: "2025-04-20T21:05:24.000Z",
      updated_at: "2025-04-20T21:05:24.000Z",
      recommendations: [
        {
          id: 22,
          finding_id: 8,
          recommendation:
            "Review and update privacy settings on all your social media accounts",
          action_url: "https://example.com/social-media-privacy",
          priority: "medium",
          created_at: "2025-04-20T21:05:24.000Z",
          updated_at: "2025-04-20T21:05:24.000Z",
        },
        {
          id: 23,
          finding_id: 8,
          recommendation:
            "Check and limit public information on your profiles (twitter.com)",
          action_url: "https://example.com/limit-profile-info",
          priority: "medium",
          created_at: "2025-04-20T21:05:24.000Z",
          updated_at: "2025-04-20T21:05:24.000Z",
        },
        {
          id: 24,
          finding_id: 8,
          recommendation:
            "Regularly monitor your digital footprint by performing periodic scans",
          action_url: "https://example.com/regular-monitoring",
          priority: "medium",
          created_at: "2025-04-20T21:05:24.000Z",
          updated_at: "2025-04-20T21:05:24.000Z",
        },
      ],
    },
    {
      id: 9,
      scan_id: 27,
      source: "reddit.com",
      data_type: "posts",
      data_value: "Reddit posts by u/toye_oy",
      sensitivity_level: "low",
      breach_date: null,
      context: null,
      created_at: "2025-04-20T21:05:24.000Z",
      updated_at: "2025-04-20T21:05:24.000Z",
      recommendations: [
        {
          id: 25,
          finding_id: 9,
          recommendation:
            "Regularly monitor your digital footprint by performing periodic scans",
          action_url: "https://example.com/regular-monitoring",
          priority: "medium",
          created_at: "2025-04-20T21:05:24.000Z",
          updated_at: "2025-04-20T21:05:24.000Z",
        },
      ],
    },
    {
      id: 10,
      scan_id: 27,
      source: "instagram.com",
      data_type: "profile",
      data_value: "Instagram profile: instagram.com/toye_oy",
      sensitivity_level: "medium",
      breach_date: null,
      context: null,
      created_at: "2025-04-20T21:05:24.000Z",
      updated_at: "2025-04-20T21:05:24.000Z",
      recommendations: [
        {
          id: 26,
          finding_id: 10,
          recommendation:
            "Review and update privacy settings on all your social media accounts",
          action_url: "https://example.com/social-media-privacy",
          priority: "medium",
          created_at: "2025-04-20T21:05:24.000Z",
          updated_at: "2025-04-20T21:05:24.000Z",
        },
        {
          id: 27,
          finding_id: 10,
          recommendation:
            "Check and limit public information on your profiles (instagram.com)",
          action_url: "https://example.com/limit-profile-info",
          priority: "medium",
          created_at: "2025-04-20T21:05:24.000Z",
          updated_at: "2025-04-20T21:05:24.000Z",
        },
        {
          id: 28,
          finding_id: 10,
          recommendation:
            "Regularly monitor your digital footprint by performing periodic scans",
          action_url: "https://example.com/regular-monitoring",
          priority: "medium",
          created_at: "2025-04-20T21:05:24.000Z",
          updated_at: "2025-04-20T21:05:24.000Z",
        },
      ],
    },
  ],
};
